### PR TITLE
Native mac bindings

### LINKED ISSUE #4: MacOS Mojave support
Hi! 

Thank you very much for taking the initiative to create a maintainable fork. I understand that this fork mainly was created for getting support for Node >=10 but another big issue that noble has is missing support for MacOS Mojave. This PR https://github.com/noble/noble/pull/840 fixes this and because of noble being unmaintained the PR author created a new package `noble-mac` - https://github.com/Timeular/noble-mac.

It would be preferable to only have one fork. Maybe https://github.com/noble/noble/pull/840 could be merged into this repository and start a discussion with the `noble-mac` author about making contributions to this repository instead?

### PR DESCRIPTION
**Pull request by geovie**
Rebase https://github.com/noble/noble/pull/840 on this repo and add latest changes from [Timeular/noble-mac](https://github.com/Timeular/noble-mac)

Fixes #4

### CODE REVIEW

**Comment by rzr** [comment]
Is any one against merging this ?

vote :) or :( on this comment

**Comment by marksyzm** [comment]
Merge please, you amazing person 👍

**Comment by BillS11** [comment]
Yes please!

**Comment by rzr** [comment]
Open position for mac developers:
https://github.com/abandonware/noble/issues/9

**Comment by rzr** [comment]
Please approve me as maintainer, then I will merge this change:
https://github.com/abandonware/noble/pull/10

Feel free to also apply:
https://abandonware.github.io/

**Comment by sebastian-stephan** [comment]
We use this PR internally. We would be glad if this gets merged. Thanks for your effort!

**Comment by rzr** [comment]
Ok I assume it's ok to be merged, it will be easy to revert if any regression,

Do you see other open patch upstream that can be merged before I made a release ?

**Comment by rzr** [comment]
Replace: https://github.com/noble/noble/pull/790

**Comment by rzr** [comment]
May I suggest to add mac build to CI/CD

**Comment by marksyzm** [comment]
Definitely a good idea!

**Pull request merged**
