### PR TITLE
Add prebuildify

### PR DESCRIPTION
**Pull request by Symbitic**
This adds prebuildify, which should allow users to download prebuilt-binaries.

This excludes a windows build at the moment; I want to make sure the macOS and Linux builds work correctly first. I'll also likely need to port bluetooth-hci-socket to prebuildify.

### CODE REVIEW

**Comment by Symbitic** [comment]
@rzr The builds are failing because node-gyp-build doesn't support Node.js 8. I think that will have to be removed from the CI. Prebuildify should still build addons compatible with that version because of NAPI.

**Comment by rzr** [comment]
so you can add a change in ci file in .github dir and disable it

**Comment by Symbitic** [comment]
@rzr It should be working. The last CI build uploaded the artifacts. You will need to create a new git tag for it to create a GitHub release.

**Comment by rzr** [comment]
please rebase and fix conflicts

**Comment by Symbitic** [comment]
I rebased and updated. It is working, but CI uses windows-2016, which GitHub will remove in March 2022. WinRT doesn't compile in the newer environments. Your choice if you want to merge now or wait.

**Comment by thegecko** [comment]
I see this was merged since the latest release, could a new release be made which includes the prebuilt binaries, please?

**Pull request merged**
