### PR TITLE
Switch from Travis CI to GitHub actions.

### PR DESCRIPTION
**Pull request by mrstegeman**

### CODE REVIEW

**Comment by mrstegeman** [comment]
https://github.com/noble/noble/pull/922

**Comment by mrstegeman** [comment]
@rzr Can you navigate here and disable the two active repos? I don't have permissions to do so.

https://travis-ci.org/organizations/abandonware/repositories

**Comment by rzr** [comment]
Done, may we also trigger npm publish on pushed tag ?

**Comment by mrstegeman** [comment]
Yes, there are lots of workflows that could be set up. For instance, see here: https://github.com/tim-hellhake/fritz-adapter/blob/master/.github/workflows/release.yml

**Pull request merged**
