### PR TITLE
Add manufacturer data files

### PR DESCRIPTION
**Pull request by pixel-shock**
This is the follow-up PR of https://github.com/abandonware/noble/pull/154

### CODE REVIEW

**Comment by rzr** [comment]
please squash commit using git rebase

**Comment by pixel-shock** [comment]
done 👍

**Review by rzr — CHANGES_REQUESTED** [review]
https://github.com/abandonware/noble/pull/156/commits/813e69a6b64c900d86a930f45cd2fb699c4603a7 is not just the csv file

**Comment by pixel-shock** [comment]
I think PR is messed up, I'll close this one ... 

**But** I don't understand how I should commit the data.csv as a single file, because the other stuff like the parser is needed for that whole thing?

I removed everything regarding the data stuff out of the other PR, so in the other PR the only change is the new "manufacturer" prop.

Next step would be the commit of the parser with the data file or am I totally wrong?

**Comment by rzr** [comment]
Let's check other changes once this PR is merged:

https://github.com/abandonware/noble/pull/158

Meanwhile if there are any changes that can optionnaly download this file can be submitted in parallel

**Pull request closed without merging**
