### PR TITLE
Revert "Add "manufacturer" prop to "Peripheral""

### PR DESCRIPTION
**Pull request by Apollon77**
This reverts commit 2af44d80

see https://github.com/abandonware/noble/pull/283#issuecomment-1369789823

@pixel-shock @rzr If you choose "option A"

### CODE REVIEW

**Comment by Apollon77** [comment]
@rzr ready depending on your decision

**Comment by rzr** [comment]
LGTM, Let's wait for other reviewers feel free to mention some of them

**Comment by Apollon77** [comment]
I mentioned the two that were involved in merging :-)

maybe @kele6ra or @bwp91 ?

**Comment by Apollon77** [comment]
... but we should not wait too long because we still have broken versions out there ...

**Comment by mmestiyak** [comment]
Hello, I was about to use this package but faced this issue `ERROR:  Could not load manufacturer list from "./manufactures-hex.json".`. is there any place i can go and get the solved version instead of waiting for merging, thank you

**Comment by Apollon77** [comment]
@mmestiyak For now ignore it because it is just logging ... Will hopefully gone "soon"

**Comment by rzr** [comment]
ok to merge ?

**Comment by Apollon77** [comment]
my argumentation and the options are listed in https://github.com/abandonware/noble/pull/283#issuecomment-1369789823 ... The fastest way to come to a new releasable version and a clean master is to merge this PR and have @pixel-shock (or who ever is interested in that feature) do another clean PR.

Other options will take much longer.

So yes from me, but in fact a second person should agree to my argumentation :-)

**Comment by kele6ra** [comment]
Hi, I think that without manufacture id base file,  or what @pixel-shock mentioned to do with it, it is useless now and mostly confuses. I thought that something wrong with my device when I run noble first time.
I am agree with @Appolon77 to roll back that commit.

**Comment by AlCalzone** [comment]
I'm with the others on this one. Logging that looks like an error is going to confuse people and cause unnecessary issues.

**Comment by rzr** [comment]
so is anyone against merging this ?

**Review by AlCalzone — APPROVED** [review]

**Comment by Apollon77** [comment]
I invite anyone to also review the release PR :-))

https://github.com/abandonware/noble/pull/290

**Pull request merged**
