### PR TITLE
Release 1.9.2-19

### PR DESCRIPTION
**Pull request by Apollon77**
Then lets bring the fixed versions of hci-socket and also noble to the world

(with basically updated dependencies)

### CODE REVIEW

**Comment by Apollon77** [comment]
Once testing works I will redo the PR ... do not merge for now

**Comment by Apollon77** [comment]
@rzr ready for release :-)

**Comment by Apollon77** [comment]
@rzr I will adress the eslint warnings in a follow up PR if you like

**Review by AlCalzone — APPROVED** [review]
If the new ESLint warnings aren't bothering the maintainer, LGTM

**Comment by rzr** [comment]
ok btw lint is welcome later, please also check github actions reports

**Pull request merged**
