### PR TITLE
[peripheral.manufacturer] - Add "manufacturer" prop to "Peripheral"

### PR DESCRIPTION
**Pull request by pixel-shock**
Hi 👋 ,

I've added a "manufacturer" prop to the "Peripheral" with Manufacture Name resolution against a JSON, which can be parsed via ```yarn parse-manufactures```

- the data.csv is downloaded from https://www.bluetooth.com/specifications/assigned-numbers/company-identifiers/

I thought it can be useful to identify a manufacturer directly while scanning devices. This can look like this:

    console.log(`Found device ${peripheral.advertisement.localName}, ${peripheral.manufacturer.name} with UUID ${peripheral.uuid}`);

Bildschirmfoto 2020-12-19 um 17 16 26

To to update the data you just have to download the new CSV from the bluetooth.com website and run ```yarn run parse-manufacturers```

Hope you'll happy about it 😉

### CODE REVIEW

**Review by rzr — COMMENTED** [review]
may the copied be commited separately and clearly indicate the source where it was downloaded or generated

**Comment by pixel-shock** [comment]
Hi,

Sorry, I don‘t really understand your comment ... do you mean the source of the manufacture codes? 
It‘s on the off. website https://www.bluetooth.com/specifications/assigned-numbers/company-identifiers/ 

there is a list and above the list there is a „CSV“ download button

**Comment by rzr** [comment]
yes please commit this file alone in a separate patch

**Comment by pixel-shock** [comment]
The file is already included in the PR scripts/manufactures/data.csv

The off. BT site has just a blob to download. So the content of the data.csv is the blob content

If you want me to seperately open PRs on the code implementation and the data source, I have to close this one and open 2 new PRs

**Comment by rzr** [comment]
yes plit split this commit in 2 (the code you actually wrote and the stuff you borrowed) 
this push force over your branch it will update this PR for @abandonware/reviewers 

Thanks

**Review by rzr — CHANGES_REQUESTED** [review]
may you commit this file separately 
 scripts/manufactures/data.csv 

and tell its orgin to make sure we don't mix licencing

**Comment by pixel-shock** [comment]
> may you commit this file separately
> scripts/manufactures/data.csv
> 
> and tell its orgin to make sure we don't mix licencing

Hi,

I removed the "data.csv" from the repo and changed the README.md content to a little "how to" update the data. So maybe we don't need to commit the data into the repo and bypass all licence issues?

**Comment by rzr** [comment]
can this be automated ?
file should be stored anyway for offline use
just isolate the commit in case someone need to revert it

**Comment by pixel-shock** [comment]
> can this be automated ?
> file should be stored anyway for offline use
> just isolate the commit in case someone need to revert it

- I whish this could be automated. Currently I could not find any URL for the CSV, it's a blob from a WordPress plugin they are using.
- I removed the generated json files from this PR

**Comment by pixel-shock** [comment]
I've opened a new PR for the data files: https://github.com/abandonware/noble/pull/156

**Review by rzr — APPROVED** [review]
LGTM

**Comment by pixel-shock** [comment]
I've cleaned up this PR into a single commit without any data-stuff like .csv or parsing stuff or json files for the new prop

**Pull request merged**
