### PR TITLE
Release 1.9.2-16

### PR DESCRIPTION
**Pull request by donavanbecker**
v1.9.2-16

ping @rzr

### CODE REVIEW

**Review by rzr — COMMENTED** [review]
there are lot of changes here ... usually i only touch manifest files
can't it be split in smaller changes ?

**Comment by donavanbecker** [comment]
Sorry about that, I have corrected it.

ping @rzr

**Comment by rzr** [comment]
please rebase

**Comment by donavanbecker** [comment]
#270

**Pull request closed without merging**
