### PR TITLE
Typecheck serviceUuids on startScanning

### PR DESCRIPTION
**Pull request by eHammarstrom**
Relates to #166 

* Protect the user from itself

Signed-off-by: Emil Hammarstrom <emil.hammarstrom@assaabloy.com>

### CODE REVIEW

**Review by rzr — COMMENTED** [review]
how to trap this error ?

**Comment by eHammarstrom** [comment]
@rzr I am not sure what you mean by your comment, but I found code like this,

`noble.startScanning(true);`

Which produced a lot of headache.
Perhaps checks like these are not the way of JavaScript, I am unfamiliar with the practices.

**Comment by rzr** [comment]
why was true used ? maybe you can merge your test with earlier line no ?

**Comment by eHammarstrom** [comment]
@rzr I did not write the user space code, so I cannot tell you why true was used.
I'll update according to your code style remaks.

**Comment by eHammarstrom** [comment]
I don't think you can merge the lines like your example, rhs is of type boolean, lhs is of type array.

**Review by rzr — COMMENTED** [review]
Are you sure that serviceUuids is a boolean?

see:
./examples/pizza/central.js:    noble.startScanning([pizzaServiceUuid], false);


If boolean then  set _scanServicesUuid can be set to false ? this code is odd to me:

1839ead3 lib/linux/bindings.js      (Sandeep Mistry  2015-07-12 15:50:44 +0000  32)   this._scanServiceUuids = serviceUuids || [];

**Review by rzr — APPROVED** [review]
LGTM , please btw fix linter mistakes in separate commit to validate checker

**Comment by rzr** [comment]
maybe node8 can be disabled in .github files

**Comment by eHammarstrom** [comment]
The error will propagate to the following builds -- I don't know how to resolve this

**Comment by rzr** [comment]
may to try to open a other PR for your lint patch to see, then I'll merge and rebase on it

**Pull request closed without merging**
