### PR TITLE
Add support for acl fragmentation

### PR DESCRIPTION
**Pull request by DeltaEvo**
ACL fragmentation is required to send ACL payload bigger than the controller buffer size, so for example if you `write` a big payload on an handle

### CODE REVIEW

**Review by rzr — APPROVED** [review]
LGTM, Please anyone double check ?

**Comment by fwcd** [comment]
Works fine for me, any blockers here?

**Comment by DeltaEvo** [comment]
Thanks :heart:

**Comment by rzr** [comment]
Feel free to test latest release and confirm there is no regressions

**Pull request merged**
