### PR TITLE
Tests tests tests

### PR DESCRIPTION
**Pull request by atrovato**
For now, target is 90% of test coverage.
But to avoid a too large PR, we can merge tests progressivly, and upgrade target according to coverage.

### CODE REVIEW

**Comment by rzr** [comment]
can this change be part of next release ?

**Comment by atrovato** [comment]
Nop, this is still draft.

**Comment by rzr** [comment]
maybe rebased

**Comment by atrovato** [comment]
@rzr I rebased it.
For information, for now, 90% coverage is expected target.

**Comment by rzr** [comment]
excellent let me know once we can merge it

**Comment by atrovato** [comment]
94.3% on my computer.
I feel tired ;)
@rzr 

Tests are not really smart, but I tried to test each event, each argument to avoid any regression, or to enforce to write test on changes.

I plugged CodeCov for coverage reporting, I'm not sure if you have to configure it on Github...

**Pull request merged**
