### PR TITLE
Release 1.9.2-15

### PR DESCRIPTION
**Pull request by ebaauw**
Second attempt.  Deleted my old fork, created a new fork, did an `npm i` and `npm version prerelease`.

### CODE REVIEW

**Comment by rzr** [comment]
last commit message should be "Release 1.9.2-15"

**Comment by ebaauw** [comment]
Ok, so I cannot use `npm version`?  Or is it possible to change the commit message?

**Comment by rzr** [comment]
git rebase -i HEAD~1 # reword

**Comment by ebaauw** [comment]
This doesn't seem to be working; let me retry.

**Pull request closed without merging**
