### PR TITLE
Release 1.9.2-24

### PR DESCRIPTION
**Pull request by donavanbecker**
@rzr

### CODE REVIEW

**Comment by donavanbecker** [comment]
probably want #324 first though.

**Comment by rzr** [comment]
MAy you align by using Release verb like

https://github.com/abandonware/noble/commit/c260768c0b00f4d2f353d06b568cbcb3419d9ce8

**Review by rzr — CHANGES_REQUESTED** [review]
Commit message will not trigger release

**Comment by donavanbecker** [comment]
> MAy you align by using Release verb like
> 
> [c260768](https://github.com/abandonware/noble/commit/c260768c0b00f4d2f353d06b568cbcb3419d9ce8)

done

**Pull request merged**
