### PR TITLE
Add tests for async functions

### PR DESCRIPTION
**Pull request by rsmeral**
Copied and modified versions of original tests of non-async functions.

### CODE REVIEW

**Comment by mrstegeman** [comment]
Can you kick the CI tests off again so we can make sure they pass? The failures were unrelated.

**Comment by rsmeral** [comment]
> Can you kick the CI tests off again so we can make sure they pass? The failures were unrelated.

The only way I found how to restart the checks is to close and re-open the PR... so I'll try do do that.

**Comment by rzr** [comment]
I triggered rebuild
maybe we can disable node-8 
it's not supported anymore:
https://nodejs.org/en/about/releases/

**Comment by rsmeral** [comment]
It seems to be failing on git checkout with `[error]fatal: reference is not a tree: ab0a524b062a08810893a4d7f291ea8e1057b2fa`.

After a bit of googling, I found https://github.com/actions/checkout/issues/23 which describes the same symptom, and suggests switching to `actions/checkout@v2` (https://github.com/actions/checkout/issues/23#issuecomment-572688577).

**Pull request merged**
