### PR TITLE
fix: issue 246, caused by race condition where _aclBuffers is not set when writeAclDataPkt is called

### PR DESCRIPTION
**Pull request by joshua-smith4**
Fix for [Issue 246](https://github.com/abandonware/noble/issues/246)

As far as I can tell, the issue is caused by a race condition where _aclBuffers are not set when writeAclDataPkt is called. I made the modification shown in this pull request and tested them on my windows setup. The issue is fixed in my system but not thoroughly tested. I would appreciate some reviews from maintainers who understand the code base much better than I.

The main change was to add a promise in front of _aclBuffers that functions needing access to it could wait on before executing. This means that writeAclDataPkt and flushAcl where changed to async functions.

### CODE REVIEW

**Comment by finaldzn** [comment]
Hello could we merge this?

**Comment by rzr** [comment]
ok waiting bots to confirm

**Comment by rzr** [comment]
Please can you please check:

https://github.com/abandonware/noble/runs/7994125818?check_suite_focus=true

Also feel free to create  a new PR to upgrade ubuntu builders to match current node LTS reqs

**Comment by joshua-smith4** [comment]
@rzr Thank you for running the tests on this pull request. I have made very slight modifications to the tests to handle the change to async on both writeAclDataPkt and flushAcl. Would you mind approving the workflows to run those tests again?

**Comment by joshua-smith4** [comment]
fixed eslint errors

**Comment by joshua-smith4** [comment]
@rzr With that final change to fix eslint errors. I believe that all tests should be passing. Are you willing to restart the tests and move this pull request on to the next step. Much appreciated!

**Comment by joshua-smith4** [comment]
When I look into the failing pipelines I just see a message "this check failed" but no details. Would someone with more access to this build process be able to provide those details to see why some (specifically the windows-based jobs) are failing?

**Comment by rzr** [comment]
May you try to issue an other simple PR to check if issue is also present
if same, please file CI bug and I'll merge this one

**Comment by donavanbecker** [comment]
@rzr Will you push a new update after this? Please or before

**Comment by rzr** [comment]
no preference, you too can do it whenever you want just commit -m "Release x.y.z" (see history)

**Comment by rzr** [comment]
Please disable win32 builder in separate PR
and rebase

**Pull request merged**
