### PR TITLE
feat: add ble5 extended advertising scanning for the hci binding

### PR DESCRIPTION
**Pull request by kele6ra**
add ble5 extended advertising scan and view with data length more then 31 byte
to scan with custom hci-usb ble5 dongle you need to add
BLUETOOTH_HCI_SOCKET_USB_VID=xxx
BLUETOOTH_HCI_SOCKET_USB_PID=xxx
parameters to your process env before scanning start
by default LE 1M and LE CODED are used

Possibly close https://github.com/abandonware/noble/issues/200

### CODE REVIEW

**Comment by rzr** [comment]
Please rebase

**Comment by kele6ra** [comment]
The next step will be realization of extended connection.

**Comment by kele6ra** [comment]
Now you can connect with zephyr ble5 hci-usb dongle

**Comment by rzr** [comment]
Please rebase and check results

**Comment by kele6ra** [comment]
Make rebase and have checked extended discovery and connect features with Windows 11 and Ubuntu 20. I found one thing with Windows OS, in https://github.com/abandonware/node-bluetooth-hci-socket/blob/master/lib/usb.js . My windows has _aclDataOutEndpoint with 0x01 address. I will make pr with trying to use 0x01 address if 0x02 address is undefined.

**Comment by kele6ra** [comment]
Sorry, I have used local linter before. Now I rebase noble with project linter.

**Comment by kele6ra** [comment]
I have fixed this issue, problem was with MTU answer message. It has ruined command queue in the gatt, when there is a wrong PDU answer from HCI.

**Pull request merged**
