### PR TITLE
[peripheral.manufacturer] - Add data csv for manufactures

### PR DESCRIPTION
**Pull request by pixel-shock**
Follow up for: https://github.com/abandonware/noble/pull/154

### CODE REVIEW

**Review by rzr — COMMENTED** [review]
Please explain where the file has been copied and copyright info in commit message,
can the .gitingore change be added in other commit ?

**Comment by pixel-shock** [comment]
> Please explain where the file has been copied and copyright info in commit message,
> can the .gitingore change be added in other commit ?

- reverted .gitignore changes
- changed commit msg including the url to the source
- as far as I know there is no License on that data ... I could not find any licence

**Review by rzr — COMMENTED** [review]
LGTM,

Lets' see if BT confirm it's ok to import this file

https://twitter.com/RzrFreeFr/status/1341709860442914817

**Comment by rzr** [comment]
I asked again at:
https://twitter.com/RzrFreeFr/status/1348294426775465984
https://www.linkedin.com/posts/rzrfreefr_peripheralmanufacturer-add-data-csv-activity-6754060960853475330-Yoc0

Feel free to make those posts more visible then we will advise if we should merge it or not, 
Does this sound like a good plan ?

**Comment by pixel-shock** [comment]
I shared it on linkedin 👌

**Comment by rzr** [comment]
No feedback yet, I also asked at:
https://www.linkedin.com/feed/update/urn:li:activity:6757028535501770752

Feel free to do the same and we will release it

**Comment by rzr** [comment]
What license would be best for this file ?

I am thinking of CC0 as suggested at:
https://www.gnu.org/licenses/license-list.en.html#NoLicense

**Comment by Apollon77** [comment]
Based on https://github.com/abandonware/noble/pull/288 and https://github.com/abandonware/noble/pull/283#issuecomment-1369789823 the basis of the PR got reverted and so we should also close this PR

**Comment by Apollon77** [comment]
@rzr

**Pull request closed without merging**
